import json

with open('data/rules_2024.json', 'r', encoding='utf-8') as f:
    rules = json.load(f)

trait_descriptions = {
    "Resourceful": "Guadagni Ispirazione Eroica al termine di un riposo lungo.",
    "Versatile": "Ottieni un talento di Origine extra e la competenza in un'abilità a tua scelta.",
    "Darkvision": "Scurovisione: Puoi vedere con luce fioca entro 18 metri come se fosse luce intensa, e nell'oscurità come se fosse luce fioca.",
    "Scurovisione (Darkvision)": "Puoi vedere con luce fioca entro 18 metri come se fosse luce intensa, e nell'oscurità come se fosse luce fioca.",
    "Elven Lineage": "Ottieni incantesimi basati sul tuo lignaggio elfico (Alto, Silvano o Drow).",
    "Fey Ancestry": "Vantaggio ai tiri salvezza per evitare o terminare la condizione Affascinato su te stesso.",
    "Keen Senses": "Ottieni competenza nell'abilità Percezione.",
    "Trance": "Non hai bisogno di dormire e la magia non può addormentarti. Finisci un riposo lungo in 4 ore di trance.",
    "Dwarven Resilience": "Vantaggio ai tiri salvezza contro veleno, e hai resistenza ai danni da veleno.",
    "Dwarven Toughness": "I tuoi punti ferita massimi aumentano di 1, e di un ulteriore 1 ogni volta che sali di livello.",
    "Stonecunning": "Come azione bonus ottieni Percezione Tellurica 18m per 10 minuti (usi pari a bonus di competenza).",
    "Brave": "Vantaggio ai tiri salvezza contro la condizione Spaventato.",
    "Halfling Nimbleness": "Puoi muoverti attraverso lo spazio di qualsiasi creatura di taglia superiore alla tua.",
    "Lucky": "Quando ottieni 1 al d20 per attacchi, prove o TS, puoi ritirare il dado e usare il nuovo risultato.",
    "Naturally Stealthy": "Puoi tentare di nasconderti anche quando oscurato da una creatura di taglia superiore.",
    "Draconic Ancestry": "Scegli un tipo di drago. Determina la tua arma a soffio e la resistenza ai danni.",
    "Breath Weapon": "Azione per esalare energia in un cono o linea. TS su Destrezza per dimezzare (1d10 + livello character).",
    "Damage Resistance": "Hai resistenza al tipo di danno associato al tuo Draconic Ancestry.",
    "Adrenaline Rush": "Puoi usare Scatto come azione bonus. Ottieni PV temporanei pari al tuo livello.",
    "Relentless Endurance": "Quando scendi a 0 PV ma non sei ucciso sul colpo, puoi scendere a 1 PV invece.",
    "Fiendish Legacy": "Ottieni Taumaturgia e altre magie al livello 3 e 5 in base al retaggio.",
    "Hellish Resistance": "Hai resistenza ai danni da Fuoco, Freddo o Veleno (in base al retaggio).",
    "Gnomish Cunning": "Vantaggio ai tiri salvezza su Intelligenza, Saggezza e Carisma contro incantesimi.",
    "Gnomish Lineage": "Ottieni i trucchetti e incantesimi in base alla tua discendenza Gnomica.",
    "Giant Ancestry": "Scegli una discendenza da un gigante per ottenere poteri unici.",
    "Large Form": "Dal 5° livello, puoi diventare taglia Grande per 10 minuti (aumenta portata e velocità).",
    "Powerful Build": "Vantaggio ai TS contro l'essere Afferrato, conti come taglia superiore per il peso trasportabile.",
    "Resistenza Celestiale (Celestial Resistance)": "Resistenza ai danni radiosi e necrotici.",
    "Mani Guaritrici (Healing Hands)": "Cura toccando una creatura per punti ferita pari al tuo numero di dadi vita.",
    "Portatore di Luce (Light Bearer)": "Conosci il trucchetto Luce.",
    "Rivelazione Celestiale (Celestial Revelation)": "Al 3° livello puoi sprigionare energia celestiale per 1 minuto (ali, luce, etc).",
    "Ascendenza Fatata (Fey Ancestry - Regole 2024)": "Vantaggio ai tiri salvezza contro la condizione Affascinato.",
    "Versatilità nelle Abilità (Skill Versatility)": "Competenza in due abilità a tua scelta.",
    "Tenacia Implacabile (Relentless Endurance)": "Quando scendi a 0 PF, torni a 1 PF. (1/Riposo Lungo).",
    "Attacchi Selvaggi (Savage Attacks)": "Critico in mischia: tira un dado di danno in più.",
    "Respiro Inesauribile (Unending Breath)": "Puoi trattenere il respiro all'infinito.",
    "Resistenza al Fulmine": "Hai resistenza ai danni da fulmine.",
    "Mescolarsi con il Vento (Mingle with the Wind)": "Conosci Stretta Folgorante. Salendo di livello ottieni Caduta Morbida e Levitare.",
    "Camminare sulla Terra (Earth Walk)": "Puoi muoverti sul terreno difficile di pietra senza spendere movimento extra.",
    "Fondersi con la Pietra (Merge with Stone)": "Conosci Interdizione alle Lame. Salendo di livello ottieni Passare Senza Tracce.",
    "Resistenza al Fuoco": "Hai resistenza ai danni da fuoco.",
    "Tendere alla Fiamma (Reach to the Blaze)": "Conosci Produrre Fiamma. Salendo di livello ottieni Mani Brucianti e Sfera Infuocata.",
    "Resistenza all'Acido": "Hai resistenza ai danni da acido.",
    "Anfibio (Amphibious)": "Puoi respirare sia in acqua che fuori.",
    "Velocità di Nuoto 30 ft": "Hai una velocità di nuoto pari al tuo movimento a terra.",
    "Richiamo dell'Onda (Call to the Wave)": "Conosci Spruzzo Velenoso. Salendo di livello ottieni Creare/Distruggere Acqua.",
    "Agilità Felina (Feline Agility)": "Puoi raddoppiare la tua velocità finché non termini il turno.",
    "Artigli del Gatto (Cat's Claws)": "I tuoi artigli sono armi naturali (1d6 + Forza tagliente).",
    "Talento del Gatto (Cat's Talent)": "Hai competenza in Percezione e Furtività.",
    "Fuga Agile (Nimble Escape)": "Puoi usare Nascondersi o Disimpegnarsi come azione bonus.",
    "Furia dei Piccoli (Fury of the Small)": "Danni extra contro creature più grandi pari al tuo livello.",
    "Mutaforma (Shapechanger)": "Come azione puoi mutare aspetto in un'altra razza umanoide.",
    "Istinti Cangianti (Changeling Instincts)": "Competenza in due abilità tra Inganno, Intimidire, Intuizione e Persuasione.",
    "Movimenti del Ragno (Spider Climb)": "Puoi scalare superfici verticali o a testa in giù senza usare le mani.",
    "Morso Vampirico (Vampiric Bite)": "Morso per recuperare punti ferita o ottenere bonus di attacco.",
    "Pegno Inquietante (Eerie Token)": "Crea un token per messaggi o telepatia a distanza.",
    "Magia Malefica (Hex Magic)": "Conosci Camuffare Se Stesso e Maleficio.",
    "Natura Immortale (Deathless Nature)": "Vantaggio ai TS contro Veleno e Malattie. Non devi mangiare o respirare.",
    "Conoscenza da una Vita Passata (Knowledge from a Past Life)": "Aggiungi 1d6 a un tiro abilità. (Usi pari a bonus competenza)."
}

rules["trait_descriptions"] = trait_descriptions

with open('data/rules_2024.json', 'w', encoding='utf-8') as f:
    json.dump(rules, f, indent=2, ensure_ascii=False)
